/**
 * Mock match data for scorecard - replace with API later
 */
export const MOCK_MATCHES = [
  {
    id: 1,
    league: 'DMT',
    status: 'upcoming',
    matchId: "21st Match - President's Trophy",
    team1: { name: 'Karachi Kids', initial: 'K', flag: 'karachi' },
    team2: { name: 'Rawalpindi Royals', initial: 'R', flag: 'rawalpindi' },
    meta: { startsIn: '1h 30m', time: 'Today 5:30 PM' },
  },
  {
    id: 2,
    league: 'TSL',
    status: 'live',
    matchId: '19th Match - WPL',
    team1: {
      name: 'Karachi Kids',
      initial: 'K',
      flag: 'karachi',
      score: '234/7',
    },
    team2: {
      name: 'Rawalpindi Royals',
      initial: 'R',
      flag: 'rawalpindi',
      score: '27/1 (4.4/50 OV, T:235)',
    },
    score1: '234/7',
    score2: '27/1 (4.4/50 OV, T:235)',
    meta: { commentary: 'Karachi Kids need 207 runs from 45 overs.' },
  },
  {
    id: 3,
    league: 'DPL',
    status: 'result',
    matchId: '26th Match, Super Six - WT20 WC Qualifier',
    team1: {
      name: 'Karachi Kids',
      initial: 'K',
      flag: 'karachi',
      score: '128',
    },
    team2: {
      name: 'Rawalpindi Royals',
      initial: 'R',
      flag: 'rawalpindi',
      score: '100 (19/20 OV, T:129)',
    },
    score1: '128',
    score2: '100 (19/20 OV, T:129)',
    meta: { commentary: 'Rawalpindi Royals won by 29 runs.' },
  },
  {
    id: 4,
    league: 'XRL',
    status: 'upcoming',
    matchId: '15th Match - XRL League',
    team1: { name: 'Karachi Kids', initial: 'K', flag: 'karachi' },
    team2: { name: 'Rawalpindi Royals', initial: 'R', flag: 'rawalpindi' },
    meta: { startsIn: '3h 15m', time: 'Today 7:00 PM' },
  },
  {
    id: 5,
    league: 'KTPL',
    status: 'live',
    matchId: '8th Match - KTPL',
    team1: {
      name: 'Karachi Kids',
      initial: 'K',
      flag: 'karachi',
      score: '156/3',
    },
    team2: {
      name: 'Rawalpindi Royals',
      initial: 'R',
      flag: 'rawalpindi',
      score: '89/2 (12/20 OV, T:157)',
    },
    score1: '156/3',
    score2: '89/2 (12/20 OV, T:157)',
    meta: { commentary: 'Rawalpindi Royals need 68 runs from 48 balls.' },
  },
  {
    id: 6,
    league: 'DMT',
    status: 'result',
    matchId: "14th Match - President's Trophy",
    team1: {
      name: 'Karachi Kids',
      initial: 'K',
      flag: 'karachi',
      score: '198/9',
    },
    team2: {
      name: 'Rawalpindi Royals',
      initial: 'R',
      flag: 'rawalpindi',
      score: '202/5 (18.2/20 OV)',
    },
    score1: '198/9',
    score2: '202/5 (18.2/20 OV)',
    meta: { commentary: 'Rawalpindi Royals won by 5 wickets.' },
  },
];
