<?php

namespace App\Models\Settlements;

use App\Models\BaseModel;

class DailyCumulativeSettlement extends BaseModel
{
    protected $fillable = [
        'date',
        'deposited_money',
        'deposited_money_count',
        'deposited_money_by_admin',
        'deposited_money_by_admin_count',
        'withdrawal_money',
        'withdrawal_money_count',
        'withdrawal_money_by_admin',
        'withdrawal_money_by_admin_count',
        'points',
        'points_credited_by_admin',
        'points_credited_by_admin_count',
        'points_credited_by_referal_code',
        'points_credited_by_referal_code_count',
        'points_credited_by_losing_bet',
        'points_credited_by_losing_bet_count',
        'points_debited_by_admin',
        'points_debited_by_admin_count',
        'points_exchange',
        'points_exchange_count',
        'coupon_points',
        'coupon_points_credited_by_admin',
        'coupon_points_credited_by_admin_count',
        'coupon_points_debited_by_admin',
        'coupon_points_debited_by_admin_count',
        'coupon_points_credited_by_agent',
        'coupon_points_credited_by_agent_count',
        'coupon_points_debited_by_agent',
        'coupon_points_debited_by_agent_count',
        'coupon_points_distribution_payment_by_agent',
        'coupon_points_distribution_payment_by_agent_count',
        'coupon_points_distribution_recovery_by_agent',
        'coupon_points_distribution_recovery_by_agent_count',
        'coupon_points_exchange',
        'coupon_points_exchange_count',
        'holding_money',
        'total_holding_money',
        'total_points',
        'total_coupon_points',
        'total_losing_money',
        'total_rolling_money',
        'total_betting_money',
        'total_betting_amount_slot',
        'total_betting_amount_casino',
        'total_refunded_money',
        'total_refunded_amount_slot',
        'total_refunded_amount_casino',
        'total_net_betting_money',
        'total_net_betting_amount_slot',
        'total_net_betting_amount_casino',
        'total_winning_money',
        'total_winning_amount_slot',
        'total_winning_amount_casino',
        'total_canceled_money',
        'total_canceled_amount_slot',
        'total_canceled_amount_casino',
        'total_net_winning_money',
        'total_net_winning_amount_slot',
        'total_net_winning_amount_casino',
        'total_betting_difference',
        'total_betting_difference_slot',
        'total_betting_difference_casino',
        'total_net_betting_difference',
        'total_net_betting_difference_slot',
        'total_net_betting_difference_casino',
        'total_jackpot_money',
        'total_bonus_money',
        'total_promo_win_money',
        'betting_money',
        'refunded_money',
        'net_betting_money',
        'winning_money',
        'canceled_money',
        'net_winning_money',
        'betting_difference',
        'net_betting_difference',
        'jackpot_money',
        'bonus_money',
        'promo_win_money',
        'first_recharge_bonus_points_after_signup',
        'first_recharge_bonus_points_after_signup_count',
        'first_recharge_bonus_points_of_day',
        'first_recharge_bonus_points_of_day_count',
        'per_recharge_bonus_points',
        'per_recharge_bonus_points_count',
        'approved_members_count',
        'requested_members_count',
        'rolling_money',
        'rolling_money_credited',
        'rolling_money_credited_count',
        'rolling_money_withdrawal',
        'rolling_money_withdrawal_count',
        'losing_money',
        'losing_money_credited',
        'losing_money_credited_count',
        'losing_money_debited',
        'losing_money_debited_count',
        'losing_money_withdrawal',
        'losing_money_withdrawal_count',
        'created_by',
        'updated_by',
        'deleted_by',
        'restored_at',
        'restored_by',
    ];

    protected $casts = [
        'date' => 'date',
        'deposited_money' => 'float',
        'deposited_money_count' => 'int',
        'deposited_money_by_admin' => 'float',
        'deposited_money_by_admin_count' => 'int',
        'withdrawal_money' => 'float',
        'withdrawal_money_count' => 'int',
        'withdrawal_money_by_admin' => 'float',
        'withdrawal_money_by_admin_count' => 'int',
        'points' => 'float',
        'points_credited_by_admin' => 'float',
        'points_credited_by_admin_count' => 'int',
        'points_credited_by_referal_code' => 'float',
        'points_credited_by_referal_code_count' => 'int',
        'points_credited_by_losing_bet' => 'float',
        'points_credited_by_losing_bet_count' => 'int',
        'points_debited_by_admin' => 'float',
        'points_debited_by_admin_count' => 'int',
        'points_exchange' => 'float',
        'points_exchange_count' => 'int',
        'coupon_points' => 'float',
        'coupon_points_credited_by_admin' => 'float',
        'coupon_points_credited_by_admin_count' => 'int',
        'coupon_points_debited_by_admin' => 'float',
        'coupon_points_debited_by_admin_count' => 'int',
        'coupon_points_credited_by_agent' => 'float',
        'coupon_points_credited_by_agent_count' => 'int',
        'coupon_points_debited_by_agent' => 'float',
        'coupon_points_debited_by_agent_count' => 'int',
        'coupon_points_distribution_payment_by_agent' => 'float',
        'coupon_points_distribution_payment_by_agent_count' => 'int',
        'coupon_points_distribution_recovery_by_agent' => 'float',
        'coupon_points_distribution_recovery_by_agent_count' => 'int',
        'coupon_points_exchange' => 'float',
        'coupon_points_exchange_count' => 'int',
        'holding_money' => 'float',
        'total_holding_money' => 'float',
        'total_points' => 'float',
        'total_coupon_points' => 'float',
        'total_losing_money' => 'float',
        'total_rolling_money' => 'float',
        'total_betting_money' => 'float',
        'total_betting_amount_slot' => 'float',
        'total_betting_amount_casino' => 'float',
        'total_refunded_money' => 'float',
        'total_refunded_amount_slot' => 'float',
        'total_refunded_amount_casino' => 'float',
        'total_net_betting_money' => 'float',
        'total_net_betting_amount_slot' => 'float',
        'total_net_betting_amount_casino' => 'float',
        'total_winning_money' => 'float',
        'total_winning_amount_slot' => 'float',
        'total_winning_amount_casino' => 'float',
        'total_canceled_money' => 'float',
        'total_canceled_amount_slot' => 'float',
        'total_canceled_amount_casino' => 'float',
        'total_net_winning_money' => 'float',
        'total_net_winning_amount_slot' => 'float',
        'total_net_winning_amount_casino' => 'float',
        'total_betting_difference' => 'float',
        'total_betting_difference_slot' => 'float',
        'total_betting_difference_casino' => 'float',
        'total_net_betting_difference' => 'float',
        'total_net_betting_difference_slot' => 'float',
        'total_net_betting_difference_casino' => 'float',
        'total_jackpot_money' => 'float',
        'total_bonus_money' => 'float',
        'total_promo_win_money' => 'float',
        'betting_money' => 'float',
        'refunded_money' => 'float',
        'net_betting_money' => 'float',
        'winning_money' => 'float',
        'canceled_money' => 'float',
        'net_winning_money' => 'float',
        'betting_difference' => 'float',
        'net_betting_difference' => 'float',
        'jackpot_money' => 'float',
        'bonus_money' => 'float',
        'promo_win_money' => 'float',
        'first_recharge_bonus_points_after_signup' => 'float',
        'first_recharge_bonus_points_after_signup_count' => 'int',
        'first_recharge_bonus_points_of_day' => 'float',
        'first_recharge_bonus_points_of_day_count' => 'int',
        'per_recharge_bonus_points' => 'float',
        'per_recharge_bonus_points_count' => 'int',
        'approved_members_count' => 'int',
        'requested_members_count' => 'int',
        'rolling_money' => 'float',
        'rolling_money_credited' => 'float',
        'rolling_money_credited_count' => 'int',
        'rolling_money_withdrawal' => 'float',
        'rolling_money_withdrawal_count' => 'int',
        'losing_money' => 'float',
        'losing_money_credited' => 'float',
        'losing_money_credited_count' => 'int',
        'losing_money_debited' => 'float',
        'losing_money_debited_count' => 'int',
        'losing_money_withdrawal' => 'float',
        'losing_money_withdrawal_count' => 'int',
        'restored_at' => 'datetime',
    ];
}
