import { NgModule } from '@angular/core';
import { TablerIconsModule } from '@luoxiao123/angular-tabler-icons';
import {
  IconCamera,
  IconHeart,
  IconBrandGithub,
  IconHome,
  IconHierarchy3,
  IconUsers,
  IconCards,
  IconWallet,
  IconCurrencyWon,
  IconAdjustmentsAlt,
  IconHours24,
  IconSettingsCog,
  IconX,
  IconPower,
  IconPoint,
  IconLockCog,
  IconCheck,
  IconBan,
  IconSettings,
  IconMenu2,
  IconGridDots,
  IconCircleFilled,
  IconSunHigh,
  IconMoon,
  IconShadow,
  IconPlus,
  IconMinus,
  IconUser,
  IconFileDescription,
  IconTrash,
  IconEdit,
  IconPlayerPause,
  IconPlayerPlay,
  IconLayoutDistributeHorizontal,
  IconLayoutDistributeVertical,
  IconShadowOff,
  IconLayoutNavbar,
  IconLayoutSidebar,
  IconLayoutSidebarRight,
  IconBuildingBank,
  IconCoins,
} from '@luoxiao123/angular-tabler-icons/icons';

const icons = {
  IconCamera,
  IconHeart,
  IconBrandGithub,
  IconHome,
  IconHierarchy3,
  IconUsers,
  IconCards,
  IconWallet,
  IconCurrencyWon,
  IconAdjustmentsAlt,
  IconHours24,
  IconSettingsCog,
  IconX,
  IconPower,
  IconPoint,
  IconLockCog,
  IconCheck,
  IconBan,
  IconSettings,
  IconMenu2,
  IconGridDots,
  IconCircleFilled,
  IconSunHigh,
  IconMoon,
  IconShadow,
  IconPlus,
  IconMinus,
  IconUser,
  IconFileDescription,
  IconTrash,
  IconEdit,
  IconPlayerPause,
  IconPlayerPlay,
  IconLayoutDistributeHorizontal,
  IconLayoutDistributeVertical,
  IconShadowOff,
  IconLayoutNavbar,
  IconLayoutSidebar,
  IconLayoutSidebarRight,
  IconBuildingBank,
  IconCoins,
};

@NgModule({
  imports: [TablerIconsModule.pick(icons)],
  exports: [TablerIconsModule],
})
export class IconsModule {}
