export { default as alert } from '@/dynamic-components/template16/modals/alert/Alert';
export { default as announcement } from '@/dynamic-components/template16/modals/announcement/Announcement';
export { default as customerService } from '@/dynamic-components/template16/modals/customer-service/CustomerService';
export { default as launchGame } from '@/dynamic-components/template16/modals/launchGame/LaunchGame';
export { default as login } from '@/dynamic-components/template16/modals/login/Login';
export { default as popup } from '@/dynamic-components/template16/modals/popup/Popup';
export { default as promotionDetail } from '@/dynamic-components/template16/modals/promotionDetail/PromotionDetail';
export { default as register } from '@/dynamic-components/template16/modals/register/Register';
export { default as transaction } from '@/dynamic-components/template16/modals/transaction/Transaction';
