<?php

namespace App\Http\Resources\v1\Settlements;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class DailySettlementResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return [
            'date' => $this->date->format('Y-m-d'),
            'deposited_money' => $this->deposited_money,
            'deposited_money_count' => $this->deposited_money_count,
            'deposited_money_by_admin' => $this->deposited_money_by_admin,
            'deposited_money_by_admin_count' => $this->deposited_money_by_admin_count,
            'withdrawal_money' => $this->withdrawal_money,
            'withdrawal_money_count' => $this->withdrawal_money_count,
            'withdrawal_money_by_admin' => $this->withdrawal_money_by_admin,
            'withdrawal_money_by_admin_count' => $this->withdrawal_money_by_admin_count,
            'wallet_points' => $this->points,
            'points_credited_by_admin' => $this->points_credited_by_admin,
            'points_credited_by_admin_count' => $this->points_credited_by_admin_count,
            'points_credited_by_referal_code' => $this->points_credited_by_referal_code,
            'points_credited_by_referal_code_count' => $this->points_credited_by_referal_code_count,
            'points_credited_by_losing_bet' => $this->points_credited_by_losing_bet,
            'points_credited_by_losing_bet_count' => $this->points_credited_by_losing_bet_count,
            'points_debited_by_admin' => $this->points_debited_by_admin,
            'points_debited_by_admin_count' => $this->points_debited_by_admin_count,
            'points_exchange' => $this->points_exchange,
            'points_exchange_count' => $this->points_exchange_count,
            'wallet_coupon_points' => $this->coupon_points,
            'coupon_points_credited_by_admin' => $this->coupon_points_credited_by_admin,
            'coupon_points_credited_by_admin_count' => $this->coupon_points_credited_by_admin_count,
            'coupon_points_debited_by_admin' => $this->coupon_points_debited_by_admin,
            'coupon_points_debited_by_admin_count' => $this->coupon_points_debited_by_admin_count,
            'coupon_points_credited_by_agent' => $this->coupon_points_credited_by_agent,
            'coupon_points_credited_by_agent_count' => $this->coupon_points_credited_by_agent_count,
            'coupon_points_debited_by_agent' => $this->coupon_points_debited_by_agent,
            'coupon_points_debited_by_agent_count' => $this->coupon_points_debited_by_agent_count,
            'coupon_points_distribution_payment_by_agent' => $this->coupon_points_distribution_payment_by_agent,
            'coupon_points_distribution_payment_by_agent_count' => $this->coupon_points_distribution_payment_by_agent_count,
            'coupon_points_distribution_recovery_by_agent' => $this->coupon_points_distribution_recovery_by_agent,
            'coupon_points_distribution_recovery_by_agent_count' => $this->coupon_points_distribution_recovery_by_agent_count,
            'coupon_points_exchange' => $this->coupon_points_exchange,
            'coupon_points_exchange_count' => $this->coupon_points_exchange_count,
            'wallet_holding_money' => $this->holding_money,
            'wallet_total_holding_money' => $this->total_holding_money,
            'wallet_total_points' => $this->total_points,
            'wallet_total_coupon_points' => $this->total_coupon_points,
            'wallet_total_losing_money' => $this->total_losing_money,
            'wallet_total_rolling_money' => $this->total_rolling_money,
            'wallet_total_betting_money' => $this->total_betting_money,
            'wallet_total_betting_amount_slot' => $this->total_betting_amount_slot,
            'wallet_total_betting_amount_casino' => $this->total_betting_amount_casino,
            'wallet_total_refunded_money' => $this->total_refunded_money,
            'wallet_total_refunded_amount_slot' => $this->total_refunded_amount_slot,
            'wallet_total_refunded_amount_casino' => $this->total_refunded_amount_casino,
            'wallet_total_net_betting_money' => $this->total_net_betting_money,
            'wallet_total_net_betting_amount_slot' => $this->total_net_betting_amount_slot,
            'wallet_total_net_betting_amount_casino' => $this->total_net_betting_amount_casino,
            'wallet_total_winning_money' => $this->total_winning_money,
            'wallet_total_winning_amount_slot' => $this->total_winning_amount_slot,
            'wallet_total_winning_amount_casino' => $this->total_winning_amount_casino,
            'wallet_total_canceled_money' => $this->total_canceled_money,
            'wallet_total_canceled_amount_slot' => $this->total_canceled_amount_slot,
            'wallet_total_canceled_amount_casino' => $this->total_canceled_amount_casino,
            'wallet_total_net_winning_money' => $this->total_net_winning_money,
            'wallet_total_net_winning_amount_slot' => $this->total_net_winning_amount_slot,
            'wallet_total_net_winning_amount_casino' => $this->total_net_winning_amount_casino,
            'wallet_total_betting_difference' => $this->total_betting_difference,
            'wallet_total_betting_difference_slot' => $this->total_betting_difference_slot,
            'wallet_total_betting_difference_casino' => $this->total_betting_difference_casino,
            'wallet_total_net_betting_difference' => $this->total_net_betting_difference,
            'wallet_total_net_betting_difference_slot' => $this->total_net_betting_difference_slot,
            'wallet_total_net_betting_difference_casino' => $this->total_net_betting_difference_casino,
            'wallet_total_jackpot_money' => $this->total_jackpot_money,
            'wallet_total_bonus_money' => $this->total_bonus_money,
            'wallet_total_promo_win_money' => $this->total_promo_win_money,
            'first_recharge_bonus_points_after_signup' => $this->first_recharge_bonus_points_after_signup,
            'first_recharge_bonus_points_after_signup_count' => $this->first_recharge_bonus_points_after_signup_count,
            'first_recharge_bonus_points_of_day' => $this->first_recharge_bonus_points_of_day,
            'first_recharge_bonus_points_of_day_count' => $this->first_recharge_bonus_points_of_day_count,
            'per_recharge_bonus_points' => $this->per_recharge_bonus_points,
            'per_recharge_bonus_points_count' => $this->per_recharge_bonus_points_count,
            'approved_members_count' => $this->approved_members_count,
            'requested_members_count' => $this->requested_members_count,
            'wallet_rolling_money' => $this->rolling_money,
            'rolling_money_credited' => $this->rolling_money_credited,
            'rolling_money_credited_count' => $this->rolling_money_credited_count,
            'rolling_money_withdrawal' => $this->rolling_money_withdrawal,
            'rolling_money_withdrawal_count' => $this->rolling_money_withdrawal_count,
            'wallet_losing_money' => $this->losing_money,
            'losing_money_credited' => $this->losing_money_credited,
            'losing_money_credited_count' => $this->losing_money_credited_count,
            'losing_money_debited' => $this->losing_money_debited,
            'losing_money_debited_count' => $this->losing_money_debited_count,
            'losing_money_withdrawal' => $this->losing_money_withdrawal,
            'losing_money_withdrawal_count' => $this->losing_money_withdrawal_count,
            'betting_money' => $this->betting_money,
            'refunded_money' => $this->refunded_money,
            'net_betting_money' => $this->net_betting_money,
            'winning_money' => $this->winning_money,
            'canceled_money' => $this->canceled_money,
            'net_winning_money' => $this->net_winning_money,
            'betting_difference' => $this->betting_difference,
            'net_betting_difference' => $this->net_betting_difference,
            'jackpot_money' => $this->jackpot_money,
            'bonus_money' => $this->bonus_money,
            'promo_win_money' => $this->promo_win_money,
        ];
    }
}
