<?php

namespace App\Settings;

use Spatie\LaravelSettings\Attributes\ShouldBeEncrypted;
use Spatie\LaravelSettings\Settings;

/**
 * Live streaming provider configuration.
 * All credentials are platform-level — Tapeya streams exclusively on its own YouTube channel.
 */
class StreamingSettings extends Settings
{
    /** OAuth redirect for Web clients — register this exact URI in Google Cloud Console. */
    public const OAUTH_REDIRECT_URI = 'http://localhost';

    /** Active provider slug: 'youtube' (cloudflare added in future) */
    public string $defaultProvider;

    /** OAuth2 Client ID from Google Cloud Console. */
    public ?string $youtubeClientId;

    /** OAuth2 Client Secret — encrypted at rest. */
    #[ShouldBeEncrypted]
    public ?string $youtubeClientSecret;

    /**
     * Platform refresh token for the Tapeya YouTube channel.
     * All matches stream here. Generated by: php artisan youtube:authorize
     */
    #[ShouldBeEncrypted]
    public ?string $youtubeRefreshToken;

    /** YouTube channel ID — UCxxxxxxxxxxxx from YouTube Studio. */
    public ?string $youtubeChannelId;

    /** Default broadcast privacy: 'public' or 'unlisted'. */
    public ?string $youtubeDefaultPrivacy;

    /**
     * Minutes to keep a match stream in idle after OBS/vMix stops before auto-ending.
     * Manual "End Stream" in backoffice always ends immediately.
     */
    public int $idleEndGraceMinutes;

    /**
     * Unused in v1 — a dedicated YouTube channel id for self-serve mobile broadcasts, kept
     * isolated from the primary match-broadcast channel. Null falls back to the primary
     * channel (current behavior). See LIVE_STREAM_MOBILE_BROADCAST.md's Trust & Safety section.
     */
    public ?string $selfServeYoutubeChannelId;

    /**
     * Alert staff when concurrent `starting`/`live` YouTube streams (admin + self-serve share
     * one channel today) reach this count. YouTube doesn't publish one fixed concurrent-broadcast
     * limit per channel — this default is a conservative starting point, not a verified ceiling.
     * Raise it once the channel's real behavior is observed. See MonitorBroadcastOperations.
     */
    public int $concurrentBroadcastAlertThreshold;

    /**
     * Daily YouTube Data API v3 quota budget in units — 10,000 is Google's default for a new
     * project; adjust to match the actual quota granted in Google Cloud Console.
     */
    public int $dailyYoutubeQuotaBudget;

    /** Alert staff once today's tracked usage (see YouTubeQuotaTracker) reaches this % of budget. */
    public int $quotaAlertThresholdPercent;

    public static function group(): string
    {
        return 'streaming';
    }
}
