<?php

namespace App\Settings;

use Spatie\LaravelSettings\Attributes\ShouldBeEncrypted;
use Spatie\LaravelSettings\Settings;

/**
 * Live streaming provider configuration.
 * All credentials are platform-level — Tapeya streams exclusively on its own YouTube channel.
 */
class StreamingSettings extends Settings
{
    /** OAuth redirect for Web clients — register this exact URI in Google Cloud Console. */
    public const OAUTH_REDIRECT_URI = 'http://localhost';

    /** Active provider slug: 'youtube' (cloudflare added in future) */
    public string $defaultProvider;

    /** OAuth2 Client ID from Google Cloud Console. */
    public ?string $youtubeClientId;

    /** OAuth2 Client Secret — encrypted at rest. */
    #[ShouldBeEncrypted]
    public ?string $youtubeClientSecret;

    /**
     * Platform refresh token for the Tapeya YouTube channel.
     * All matches stream here. Generated by: php artisan youtube:authorize
     */
    #[ShouldBeEncrypted]
    public ?string $youtubeRefreshToken;

    /** YouTube channel ID — UCxxxxxxxxxxxx from YouTube Studio. */
    public ?string $youtubeChannelId;

    /** Default broadcast privacy: 'public' or 'unlisted'. */
    public ?string $youtubeDefaultPrivacy;

    public static function group(): string
    {
        return 'streaming';
    }
}
