[supervisord]
nodaemon=true
loglevel = info
logfile=/usr/src/app/supervisord.log
pidfile=/usr/src/app/supervisord.pid

[program:php-fpm]
priority=5
command=php-fpm
autostart=true
autorestart=true
user=www-data
stderr_logfile_maxbytes=0
stdout_logfile_maxbytes=0

# Because we installed Laravel Horizon so no need to run queue:work
# [program:laravel-queue]
# process_name=%(program_name)s_%(process_num)02d
# command=php /usr/src/app/artisan queue:work --sleep=3 --tries=3
# autostart=true
# autorestart=true
# user=www-data
# numprocs=1
# redirect_stderr=true
# stdout_logfile=/usr/src/app/storage/logs/supervisor.log

[program:artisan-scheduler]
process_name=%(program_name)s_%(process_num)03d
numprocs=1
redirect_stderr=true
command=php /usr/src/app/artisan schedule:work
autostart=true
autorestart=true
user=www-data
stdout_logfile=/usr/src/app/storage/logs/schedule.log
stderr_logfile=/usr/src/app/storage/logs/schedule_error.log

[program:horizon]
process_name=%(program_name)s
command=php /usr/src/app/artisan horizon
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/usr/src/app/storage/logs/horizon.log
stderr_logfile=/usr/src/app/storage/logs/horizon_error.log
stopwaitsecs=3600
