<?php

namespace App\Http\Resources\v1\User\Wallet;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class UserWalletResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return [
            'holding_money' => $this->holding_money,
            'points' => $this->points,
            'points_credited_by_admin' => $this->points_credited_by_admin,
            'points_credited_by_admin_count' => $this->points_credited_by_admin_count,
            'points_credited_by_referal_code' => $this->points_credited_by_referal_code,
            'points_credited_by_referal_code_count' => $this->points_credited_by_referal_code_count,
            'points_credited_by_losing_bet' => $this->points_credited_by_losing_bet,
            'points_credited_by_losing_bet_count' => $this->points_credited_by_losing_bet_count,
            'points_debited_by_admin' => $this->points_debited_by_admin,
            'points_debited_by_admin_count' => $this->points_debited_by_admin_count,
            'points_exchange' => $this->points_exchange,
            'points_exchange_count' => $this->points_exchange_count,
            'coupon_points' => $this->coupon_points,
            'coupon_points_credited_by_admin' => $this->coupon_points_credited_by_admin,
            'coupon_points_credited_by_admin_count' => $this->coupon_points_credited_by_admin_count,
            'coupon_points_debited_by_admin' => $this->coupon_points_debited_by_admin,
            'coupon_points_debited_by_admin_count' => $this->coupon_points_debited_by_admin_count,
            'coupon_points_credited_by_agent' => $this->coupon_points_credited_by_agent,
            'coupon_points_credited_by_agent_count' => $this->coupon_points_credited_by_agent_count,
            'coupon_points_debited_by_agent' => $this->coupon_points_debited_by_agent,
            'coupon_points_debited_by_agent_count' => $this->coupon_points_debited_by_agent_count,
            'coupon_points_exchange' => $this->coupon_points_exchange,
            'coupon_points_exchange_count' => $this->coupon_points_exchange_count,
            'deposited_money' => $this->deposited_money,
            'deposited_money_count' => $this->deposited_money_count,
            'deposited_money_by_admin' => $this->deposited_money_by_admin,
            'deposited_money_by_admin_count' => $this->deposited_money_by_admin_count,
            'withdrawal_money' => $this->withdrawal_money,
            'withdrawal_money_count' => $this->withdrawal_money_count,
            'withdrawal_money_by_admin' => $this->withdrawal_money_by_admin,
            'withdrawal_money_by_admin_count' => $this->withdrawal_money_by_admin_count,
            'last_deposited_money_at' => $this->last_deposited_money_at,
            'last_deposited_money_by_admin_at' => $this->last_deposited_money_by_admin_at,
            'last_withdrawal_money_at' => $this->last_withdrawal_money_at,
            'last_withdrawal_money_by_admin_at' => $this->last_withdrawal_money_by_admin_at,
            'last_points_exchanged_at' => $this->last_points_exchanged_at,
            'last_coupon_points_exchanged_at' => $this->last_coupon_points_exchanged_at,
            'last_points_credited_by_admin_at' => $this->last_points_credited_by_admin_at,
            'last_points_credited_by_referal_code_at' => $this->last_points_credited_by_referal_code_at,
            'last_points_credited_by_losing_bet_at' => $this->last_points_credited_by_losing_bet_at,
            'last_points_debited_by_admin_at' => $this->last_points_debited_by_admin_at,
            'last_coupon_points_credited_by_admin_at' => $this->last_coupon_points_credited_by_admin_at,
            'last_coupon_points_debited_by_admin_at' => $this->last_coupon_points_debited_by_admin_at,
            'last_coupon_points_credited_by_agent_at' => $this->last_coupon_points_credited_by_agent_at,
            'last_coupon_points_debited_by_agent_at' => $this->last_coupon_points_debited_by_agent_at,
            'rolling_money' => $this->rolling_money,
            'rolling_money_credited' => $this->rolling_money_credited,
            'rolling_money_credited_count' => $this->rolling_money_credited_count,
            'last_rolling_money_credited_at' => $this->last_rolling_money_credited_at,
            'rolling_money_withdrawal' => $this->rolling_money_withdrawal,
            'rolling_money_withdrawal_count' => $this->rolling_money_withdrawal_count,
            'last_rolling_money_withdrawal_at' => $this->last_rolling_money_withdrawal_at,
            'losing_money' => $this->losing_money,
            'losing_money_credited' => $this->losing_money_credited,
            'losing_money_credited_count' => $this->losing_money_credited_count,
            'last_losing_money_credited_at' => $this->last_losing_money_credited_at,
            'losing_money_debited' => $this->losing_money_debited,
            'losing_money_debited_count' => $this->losing_money_debited_count,
            'last_losing_money_debited_at' => $this->last_losing_money_debited_at,
            'losing_money_withdrawal' => $this->losing_money_withdrawal,
            'losing_money_withdrawal_count' => $this->losing_money_withdrawal_count,
            'last_losing_money_withdrawal_at' => $this->last_losing_money_withdrawal_at,
            'total_holding_money' => $this->total_holding_money,
            'total_points' => $this->total_points,
            'total_coupon_points' => $this->total_coupon_points,
            'total_losing_money' => $this->total_losing_money,
            'total_rolling_money' => $this->total_rolling_money,
            'total_betting_money' => $this->total_betting_money,
            'total_betting_amount_slot' => $this->total_betting_amount_slot,
            'total_betting_amount_casino' => $this->total_betting_amount_casino,
            'total_refunded_money' => $this->total_refunded_money,
            'total_refunded_amount_slot' => $this->total_refunded_amount_slot,
            'total_refunded_amount_casino' => $this->total_refunded_amount_casino,
            'total_net_betting_money' => $this->total_net_betting_money,
            'total_net_betting_amount_slot' => $this->total_net_betting_amount_slot,
            'total_net_betting_amount_casino' => $this->total_net_betting_amount_casino,
            'total_winning_money' => $this->total_winning_money,
            'total_winning_amount_slot' => $this->total_winning_amount_slot,
            'total_winning_amount_casino' => $this->total_winning_amount_casino,
            'total_canceled_money' => $this->total_canceled_money,
            'total_canceled_amount_slot' => $this->total_canceled_amount_slot,
            'total_canceled_amount_casino' => $this->total_canceled_amount_casino,
            'total_net_winning_money' => $this->total_net_winning_money,
            'total_net_winning_amount_slot' => $this->total_net_winning_amount_slot,
            'total_net_winning_amount_casino' => $this->total_net_winning_amount_casino,
            'total_betting_difference' => $this->total_betting_difference,
            'total_betting_difference_slot' => $this->total_betting_difference_slot,
            'total_betting_difference_casino' => $this->total_betting_difference_casino,
            'total_net_betting_difference' => $this->total_net_betting_difference,
            'total_net_betting_difference_slot' => $this->total_net_betting_difference_slot,
            'total_net_betting_difference_casino' => $this->total_net_betting_difference_casino,
            'total_jackpot_money' => $this->total_jackpot_money,
            'total_bonus_money' => $this->total_bonus_money,
            'total_promo_win_money' => $this->total_promo_win_money,
        ];
    }
}
